### ISSUE TITLE
説明ページを綺麗にする

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#1]
```yaml
start_date: 2022/3/19
due_date: 2022/3/26
progress: 0.1
parent: 0
```
