### ISSUE TITLE
作成時にすぐ遷移しないようにする

### ISSUE THREAD

**Issue by ktsg-lamact** [lamact/LonpaManage#11]
```yaml
start_date: 2022/1/29
due_date: 2022/1/29
progress: 1
parent: 0
```
