### ISSUE TITLE
初回ログイン時の情報投入必須化

### ISSUE THREAD

**Issue by ktsg-lamact** [lamact/LonpaManage#12]
```yaml
start_date: 2022/2/12
due_date: 2022/2/27
progress: 1
parent: 0
```
