### ISSUE TITLE
トップデザインのデザイン更改

### ISSUE THREAD

**Issue by ktsg-lamact** [lamact/LonpaManage#13]
```yaml
start_date: 2022/2/26
due_date: 2022/3/20
progress: 1
parent: 0
```
