### ISSUE TITLE
検索のランキングを日時で自動更新するバッチ処理的な奴

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#16]
```yaml
start_date: 2022/1/29
due_date: 2022/2/18
progress: 1
parent: 0
```
