### ISSUE TITLE
論拠の横スワイプの挙動修正その１

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#18]
```yaml
start_date: 2022/1/31
due_date: 2022/2/6
progress: 1
parent: 0
```
