### ISSUE TITLE
Lonpa 投票シール化

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#2]
```yaml
start_date: 2022/1/8
due_date: 2022/1/14
progress: 1
parent: 0
```
