### ISSUE TITLE
コメント更新の自動画面反映

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#21]
```yaml
start_date: 2022/2/5
due_date: 2022/2/12
progress: 1
parent: 0
```
