### ISSUE TITLE
他の人の論拠更新を取り込んで，自動反映

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#22]
```yaml
start_date: 2022/2/26
due_date: 2022/3/6
progress: 1
parent: 0
```
