### ISSUE TITLE
バリデーションチェックを作る(URLは貼り付けさせない，140文字未満じゃないと記入させない)

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#23]
```yaml
start_date: 2022/3/5
due_date: 2022/3/13
progress: 0.1
parent: 0
```
