### ISSUE TITLE
グラフやコメントをモーダルじゃなくて画面表示に変更

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#24]
```yaml
start_date: 2022/2/12
due_date: 2022/2/20
progress: 1
parent: 0
```
