### ISSUE TITLE
voteテーブルの中に，votedParentLonpaIdを作る

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#25]
```yaml
start_date: 2022/2/12
due_date: 2022/2/13
progress: 1
parent: 0
```
