### ISSUE TITLE
Lonpa詳細モーダルを作る

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#27]
```yaml
start_date: 2022/2/12
due_date: 2022/2/20
progress: 1
parent: 0
```
