### ISSUE TITLE
論拠140文字書けるように，smallwidthのレイアウト変更

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#28]
```yaml
start_date: 2022/2/12
due_date: 2022/2/27
progress: 1
parent: 0
```
