### ISSUE TITLE
セッティング画面の作成日の表示がおかしい　2022/02/19 01:78

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#29]
```yaml
start_date: 2022/4/17
due_date: 2022/4/17
progress: 0.1
parent: 0
```
