### ISSUE TITLE
ローディングアニメーション

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#3]
```yaml
start_date: 2022/1/8
due_date: 2022/1/14
progress: 1
parent: 0
```
