### ISSUE TITLE
test01でログイン時，voteに情報が入らない？

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#30]
```yaml
start_date: 2022/4/17
due_date: 2022/4/17
progress: 0.1
parent: 0
```
