### ISSUE TITLE
lonpa画面の盛り上がり度評価に変更（今は論拠単位で得点化しているので変える）

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#31]
```yaml
start_date: 2022/3/5
due_date: 2022/3/13
progress: 0.1
parent: 0
```
