### ISSUE TITLE
ランキングが一つもないと，TOP画面でエラーになる

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#32]
```yaml
start_date: 2022/4/17
due_date: 2022/4/17
progress: 0.1
parent: 0
```
