### ISSUE TITLE
投票先が変わった際に，voteに書いた内容も消す

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#34]
```yaml
start_date: 2022/3/12
due_date: 2022/3/12
progress: 0.1
parent: 0
```
