### ISSUE TITLE
画像の圧縮と，アップロードの改修

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#39]
```yaml
start_date: 2022/4/9
due_date: 2022/4/9
progress: 0.1
parent: 0
```
