### ISSUE TITLE
プレパラートのイメージ変更その１

### ISSUE THREAD

**Issue by ktsg-lamact** [lamact/LonpaManage#6]
```yaml
start_date: 2022/1/15
due_date: 2022/2/6
progress: 1
parent: 0
```
