### ISSUE TITLE
グラフ機能の表示をよくする

### ISSUE THREAD

**Issue by jtky8238** [lamact/LonpaManage#8]
```yaml
start_date: 2022/4/23
due_date: 2022/5/1
progress: 0.1
parent: 0
```
